### ISSUE TITLE
Make left side menu sticky

### ISSUE THREAD

**Issue by scisco** [developmentseed/documentation-devseed-theme#6]
Currently the left side menu scrolls up.

Example: http://devseed.com/kes/

![kes_0_1_6___documentation_and_earthdata_login](https://user-images.githubusercontent.com/1933118/31236265-a4723aaa-a9c1-11e7-9f1c-62e354ba8c9f.png)

**Comment by prescottprue** [comment]
Also noticing this. Removing the height param from `page__header` did the trick for me:

![image](https://user-images.githubusercontent.com/2992224/46939634-a8d49a80-d01b-11e8-8184-e427f55981b6.png)


It appears to be [this line](https://github.com/developmentseed/documentation-devseed-theme/blob/4189761b7735b1ee198f6b68475d3df23e8cc846/src/assets/style.css#L116)

**Comment by scisco** [comment]
@prescottprue it'd be great if you could issue a PR for this.

**Comment by fabiocaccamo** [comment]
@prescottprue removing the height as you suggested just solves half of the problem.

Left sidebar should be fixed on left and should not scroll together with main content.

**Comment by fabiocaccamo** [comment]
Is this project still active?
